version: "2"

run:
  timeout: 5m
  tests: true

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - gocritic
    - govet
    - ineffassign
    - revive
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - unused
    - wastedassign

  settings:
    errcheck:
      exclude-functions:
        - (*database/sql.Rows).Close
        - (*os.File).Close
    revive:
      rules:
        - name: context-as-argument
        - name: empty-block
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        - name: indent-error-flow
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: superfluous-else
        - name: time-naming
        - name: unreachable-code
        - name: unused-parameter
        - name: var-declaration
